import { z } from "zod";
import { poolSchema, poolDetailSchema } from "@/schemas/pools";
import { mockLessonList } from "@/lib/home/mockLessonsData";

type Pool = z.infer<typeof poolSchema>;
type PoolDetail = z.infer<typeof poolDetailSchema>;

const toLesson = (l: (typeof mockLessonList)[number]) => ({
  id: l.id,
  academyName: l.academyName,
  academyImageUrl: l.academyImageUrl,
  keyword: l.keyword,
  lessonName: l.lessonName,
  level: l.level,
  price: l.price ?? "",
});

export const mockPools: Pool[] = [
  {
    id: 1,
    poolName: "잠실실내수영장",
    poolAddress: "서울 송파구 올림픽로 240",
    region: "송파",
    imageUrl: null,
    latitude: 37.5126,
    longitude: 127.0769,
  },
  {
    id: 2,
    poolName: "올림픽수영장",
    poolAddress: "서울 송파구 올림픽로 424",
    region: "송파",
    imageUrl: null,
    latitude: 37.5219,
    longitude: 127.0822,
  },
  {
    id: 3,
    poolName: "뚝섬한강공원수영장",
    poolAddress: "서울 광진구 강변북로 139",
    region: "광진",
    imageUrl: null,
    latitude: 37.5295,
    longitude: 127.0667,
  },
  {
    id: 4,
    poolName: "노원실내수영장",
    poolAddress: "서울 노원구 동일로 1321",
    region: "노원",
    imageUrl: null,
    latitude: 37.6556,
    longitude: 127.0763,
  },
  {
    id: 5,
    poolName: "마포구민체육센터수영장",
    poolAddress: "서울 마포구 월드컵북로 400",
    region: "마포",
    imageUrl: null,
    latitude: 37.5683,
    longitude: 126.9077,
  },
];

export const mockPoolDetails: PoolDetail[] = [
  {
    id: 1,
    poolName: "잠실실내수영장",
    poolAddress: "서울 송파구 올림픽로 240",
    region: "송파",
    operatingHours: "06:00 ~ 22:00",
    closingDays: "매주 월요일, 공휴일",
    contact: "02-410-1234",
    laneLength: 50,
    laneCount: 8,
    maxDepth: 1.8,
    minDepth: 1.2,
    facilities: "샤워실, 락커룸, 주차장",
    latitude: 37.5126,
    longitude: 127.0769,
    poolImages: [{ repImage: true, imageUrl: "/empty/swimpool_default.png" }],
    lessons: [toLesson(mockLessonList[0]), toLesson(mockLessonList[1])],
  },
  {
    id: 2,
    poolName: "올림픽수영장",
    poolAddress: "서울 송파구 올림픽로 424",
    region: "송파",
    operatingHours: "06:00 ~ 21:00",
    closingDays: "매주 화요일",
    contact: "02-410-5678",
    laneLength: 50,
    laneCount: 10,
    maxDepth: 2.0,
    minDepth: 1.4,
    facilities: "샤워실, 락커룸, 주차장, 카페테리아",
    latitude: 37.5219,
    longitude: 127.0822,
    poolImages: [{ repImage: true, imageUrl: "/empty/swimpool_default.png" }],
    lessons: [toLesson(mockLessonList[2])],
  },
  {
    id: 3,
    poolName: "뚝섬한강공원수영장",
    poolAddress: "서울 광진구 강변북로 139",
    region: "광진",
    operatingHours: "07:00 ~ 20:00",
    closingDays: "매주 월요일",
    contact: "02-3780-0561",
    laneLength: 25,
    laneCount: 6,
    maxDepth: 1.6,
    minDepth: 1.0,
    facilities: "샤워실, 락커룸",
    latitude: 37.5295,
    longitude: 127.0667,
    poolImages: [{ repImage: true, imageUrl: "/empty/swimpool_default.png" }],
    lessons: [toLesson(mockLessonList[3])],
  },
  {
    id: 4,
    poolName: "노원실내수영장",
    poolAddress: "서울 노원구 동일로 1321",
    region: "노원",
    operatingHours: "06:00 ~ 22:00",
    closingDays: "매주 월요일, 명절",
    contact: "02-950-0001",
    laneLength: 25,
    laneCount: 6,
    maxDepth: 1.6,
    minDepth: 1.0,
    facilities: "샤워실, 락커룸, 주차장",
    latitude: 37.6556,
    longitude: 127.0763,
    poolImages: [{ repImage: true, imageUrl: "/empty/swimpool_default.png" }],
    lessons: [toLesson(mockLessonList[4])],
  },
  {
    id: 5,
    poolName: "마포구민체육센터수영장",
    poolAddress: "서울 마포구 월드컵북로 400",
    region: "마포",
    operatingHours: "06:00 ~ 21:30",
    closingDays: "매주 화요일",
    contact: "02-3153-9900",
    laneLength: 25,
    laneCount: 5,
    maxDepth: 1.5,
    minDepth: 1.0,
    facilities: "샤워실, 락커룸, 주차장, 헬스장",
    latitude: 37.5683,
    longitude: 126.9077,
    poolImages: [{ repImage: true, imageUrl: "/empty/swimpool_default.png" }],
    lessons: [toLesson(mockLessonList[5])],
  },
];
