openapi: 3.0.0
info:
  title: Dive In Swimming Lesson API
  description: 수영 수업 관리 및 정보를 제공하는 API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.dive.in
    description: Production server

paths:
  /lessons:
    get:
      summary: 모든 수영 수업 목록 조회
      tags:
        - Swimming Lessons
      responses:
        "200":
          description: 수영 수업 목록을 성공적으로 조회
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lesson"
        "400":
          description: 잘못된 요청 파라미터
        "500":
          description: 서버 오류 발생

  /lessons/{id}:
    get:
      summary: 특정 수영 수업 상세 정보 조회
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 수영 수업의 고유 ID
      responses:
        "200":
          description: 수영 수업 상세 정보를 성공적으로 조회
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LessonDetail"
        "404":
          description: 해당 ID의 수영 수업을 찾을 수 없음
        "500":
          description: 서버 오류 발생

components:
  schemas:
    Lesson:
      type: object
      properties:
        id:
          type: integer
          description: 수업의 고유 id
        instructor_logo:
          type: string
          description: 강사의 로고 이미지 URL
        instructor_name:
          type: string
          description: 강사의 이름
        lesson_name:
          type: string
          description: 수업 이름
        level:
          type: string
          description: 수업 난이도
        tags:
          type: string
          description: 수업 태그들
        description:
          type: string
          description: 수업 설명
        price:
          type: integer
          description: 수업 가격
        times:
          type: integer
          description: 수업 횟수
      example:
        id: 1
        instructor_logo: "https://www.dive.in/instructor/1.jpg"
        instructor_name: "김수영"
        lesson_name: "접영 기초"
        level: "초급"
        tags: "접영,배영,다이빙"
        description: "접영 기초 수업입니다."
        price: 60000
        times: 1

    LessonDetail:
      type: object
      properties:
        id:
          type: integer
          description: 수업의 고유 id
        instructor_logo:
          type: string
          description: 강사의 로고 이미지 URL
        instructor_name:
          type: string
          description: 강사의 이름
        lesson_name:
          type: string
          description: 수업 이름
        description:
          type: string
          description: 수업 설명
        price:
          type: integer
          description: 수업 가격
        times:
          type: integer
          description: 수업 횟수
        location:
          type: string
          description: 수업 장소
        time:
          type: string
          description: 수업 시간
        max_students:
          type: integer
          description: 모집 인원
        images:
          type: array
          description: 수업 이미지들
          items:
            type: string
            format: uri
        apply_link:
          type: array
          description: 수업 신청 링크
          items:
            type: object
            properties:
              url:
                type: string
                description: 링크 URL
              type:
                type: string
                description: 링크 타입
      example:
        id: 1
        instructor_logo: "https://www.dive.in/instructor/1.jpg"
        instructor_name: "김수영"
        lesson_name: "접영 기초"
        description: "접영 기초 수업입니다."
        price: 60000
        times: 1
        location: "서울 송파구 올림픽 수영장"
        time: "매주 월요일 19:00 ~ 20:00"
        max_students: 10
        images:
          [
            "https://www.dive.in/lesson/1.jpg",
            "https://www.dive.in/lesson/2.jpg",
          ]
        apply_link:
          [
            { type: "네이버 카페", url: "https://cafe.naver.com/dive.in" },
            { type: "카카오톡", url: "https://open.kakao.com/o/gd8f7d" },
            { type: "인스타그램", url: "https://www.instagram.com/dive.in" },
          ]
