openapi: 3.0.0
info:
  title: Dive In Swimming Pool API
  description: 수영장 관리 및 정보를 제공하는 API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.dive.in
    description: Production server

paths:
  /pools:
    get:
      summary: 모든 수영장 목록 조회
      tags:
        - Swimming Pools
      responses:
        "200":
          description: 수영장 목록을 성공적으로 조회
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pool"
        "400":
          description: 잘못된 요청 파라미터
        "500":
          description: 서버 오류 발생

  /pools/{id}:
    get:
      summary: 특정 수영장 상세 정보 조회
      tags:
        - Swimming Pools
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 수영장의 고유 ID
      responses:
        "200":
          description: 수영장 상세 정보를 성공적으로 조회
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PoolDetail"
        "404":
          description: 해당 ID의 수영장을 찾을 수 없음
        "500":
          description: 서버 오류 발생

components:
  schemas:
    Pool:
      type: object
      properties:
        id:
          type: integer
          description: 수영장 고유 ID
        name:
          type: string
          description: 수영장 이름
        location:
          type: string
          description: 수영장이 위치한 주소
        region:
          type: string
          description: 칩에 사용할 지역
        image:
          type: string
          description: 이미지 주소
      example:
        id: 1
        name: 올림픽 수영장
        location: 서울 송파구 올림픽로 424
        region: 서울 송파구
        image: https://localhost:8080/images/abcd.png

    PoolDetail:
      type: object
      properties:
        id:
          type: integer
          description: 수영장 고유 ID
        name:
          type: string
          description: 수영장 이름
        location:
          type: string
          description: 수영장 주소
        contactNumber:
          type: string
          description: 수영장 전화번호
        images:
          type: array
          description: 수영장 이미지들
          items:
            type: string
            format: uri
      example:
        id: 1
        name: 올림픽 수영장
        location: 서울 송파구 올림픽로 424
        region: 서울 송파구
        images:
          [
            "https://localhost:8080/images/swim1.png",
            "https://localhost:8080/images/swim2.png",
            "https://localhost:8080/images/swim3.png",
          ]
